name: Scheduled Jobs

on:
    schedule:
        - cron: "0 0 * * 2,5" # 毎週火曜日と金曜日の0:00に実行
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
jobs:
    run_script:
        name: Run Marketplace Script
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "14"

            - name: Install dependencies
              run: npm install fs axios

            - name: Run script
              run: node ../../logseq-marketplace/marketplace.cjs
